In [7]:
#from python lists
import numpy as np
array = np.array([1,2,3])
print(array)

[1 2 3]


In [17]:
#zeros and ones arrays
import numpy as np
zeros = np.zeros((2,3)) #2 and 3 are filled with zeros
ones = np.ones((3,2)) #4 and 5 are filled with ones
print(zeros,ones)

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
#array of a constant value
import numpy as np
full_array = np.full((2,2),7) #2x2 array are filled with 7
print(full_array)

[[7 7]
 [7 7]]


In [31]:
#Range of values
import numpy as np
range_array = np.arange(0,10,2) #array of values from 0 to 10 with step 2
print(range_array)

[0 2 4 6 8]


In [33]:
#linspace(evenly spaced values)
import numpy as np
random_array = np.random.random((2,2)) #random values between 0 and 1
print(random_array)

[[0.63573344 0.34189245]
 [0.41059203 0.64902153]]


In [40]:
#to find the datatype of a array
import numpy as np
array = np.array([1,2,3], dtype=np.float32) #we have per defined the datatype and bit(32,64)
print(array)
print(array.dtype)

[1. 2. 3.]
float32


In [48]:
#to find the data type of a array
import numpy as np
array = np.array([1,2,3]) 
print(array)
print(array.dtype)
array_float=np.array([1.20,5.22])
print(array_float)
print(array_float.dtype)
array_bool = np.array([True,False])
print(array_bool)
print(array_bool.dtype)
array_complex = np.array([1 + 2j])
print(array_complex)
print(array_complex.dtype)

[1 2 3]
int64
[1.2  5.22]
float64
[ True False]
bool
[1.+2.j]
complex128
